import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import NavMenu from '../components/NavMenu'

const inter = Inter({ subsets: ['latin'] })

export default function Home(serverdata) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.dashboardpainel}>
          {serverdata.serverdata.map(el => {
            return <div className={styles.itemcard}>
              <img src={el.img} alt="" />
              <li>{el.descri}</li>
              <span>{el.date}</span>
            </div>
          })}
        </div>
        <NavMenu/>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/server")
  const serverdata = await res.json()

  return {
    props: {
      serverdata: serverdata
    }
  }
}
